/**
 * Created by nairu on 2016/10/25.
 */
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const ON_ERROR  = 'ON_ERROR';
export const RECEIVE_USER_BY_PHONE = 'RECEIVE_USER_BY_PHONE';
export const CHANGE_TAB = 'CHANGE_TAB';
export const MARK_RESOLVE = 'MARK_RESOLVE';
export const GET_DOCUMENT_STATISTIC = 'GET_DOCUMENT_STATISTIC';
export const GET_ORDER_STATISTIC = 'GET_ORDER_STATISTIC';
